# This file tells Render.com how to build and run your web service.
# If this file is present in your repository, Render will automatically configure the service.

services:
  # A unique name for your service
  - name: restaurant-queue-system
    # The type of service. 'web' means it's a web server.
    type: web
    # The runtime environment
    env: python
    # The command to install dependencies.
    buildCommand: "pip install -r requirements.txt"
    # The command to start the web server.
    # We use Gunicorn, a production-ready WSGI server.
    # It will run the 'app' object from the 'app.py' file.
    # $PORT is an environment variable provided by Render.
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT app:app"
    # Specifies the plan for this service (e.g., free tier).
    plan: free
